[package]
org = "sahan_tharaka"
name = "accessable_api"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerinax/mongodb" = "1.10.0"
"ballerina/http" = "2.10.12"
"ballerina/mime" = "2.9.0"